### ISSUE TITLE
input files

### ISSUE THREAD

**Issue by zz-xiao** [Biometris/statgenGWAS#3]
Dear developers,  
I am preparing the input files to try your package. I used your example data as models to prepare markers file and map file. it did not accept my SNP names which are consisted of chr and pos with minor allele appened (eg. 1:3003_A), which is produced by plink while preparing the converted snps in numerical. it seems a problem and cannot match the map file with the function of "createGData". 
can I get your help with this?

**Comment by BartJanvanRossum** [comment]
Closing this since I think this was solve after mail contact we had. If not please reopen and I will have a look
