### ISSUE TITLE
Plot title and axis labels

### ISSUE THREAD

**Issue by JunxiFeng** [Biometris/statgenGWAS#5]
How do I add a title for the plot and how do I change the labels in the axis?

Thanks!

**Comment by BartJanvanRossum** [comment]
In the current CRAN version of the package editing the plot title is not possible.  It will be included in the next release and is already in the latest development version that can be installed as follows:
```r
remotes::install_github("Biometris/statgenGWAS", ref = "develop", dependencies = TRUE) 
```
After installing this version you can use ```title = ...``` to customize the plot title.

For changing the x-axis labels in the manhattan plot use ```xlab = ...```
